/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary": "var(--color-primary)",
        "on-secondary-fixed": "#00105b",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "ink-muted": "var(--color-ink-muted)",
        "tertiary-fixed": "#ffdbca",
        "primary-active": "var(--color-primary-active)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "accent-teal": "#2a9d99",
        "on-background": "#181c22",
        "on-secondary": "#ffffff",
        "surface-container-low": "var(--color-surface-container-low)",
        "accent-brown": "#523410",
        "ink": "var(--color-ink)",
        "hairline": "var(--color-hairline)",
        "primary-fixed-dim": "#a8c8ff",
        "on-surface": "var(--color-on-surface)",
        "accent-purple": "#d6b6f6",
        "surface-variant": "#e0e2eb",
        "on-tertiary-container": "#fffeff",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-surface": "#2d3037",
        "on-primary-fixed-variant": "#00468a",
        "accent-sky": "#62aef0",
        "surface": "var(--color-surface)",
        "ink-secondary": "var(--color-ink-secondary)",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "accent-orange-deep": "#793400",
        "tertiary-fixed-dim": "#ffb68f",
        "inverse-on-surface": "#eef0fa",
        "error-container": "#ffdad6",
        "accent-purple-deep": "#391c57",
        "secondary-container": "#97a5fe",
        "on-primary": "var(--color-on-primary)",
        "surface-bright": "#f9f9ff",
        "outline-variant": "var(--color-outline-variant)",
        "secondary-fixed": "#dee0ff",
        "accent-orange": "#dd5b00",
        "tertiary-container": "#c15600",
        "secondary-fixed-dim": "#bac3ff",
        "ink-faint": "var(--color-ink-faint)",
        "surface-tint": "#005eb4",
        "background": "#f9f9ff",
        "on-tertiary-fixed-variant": "#773200",
        "canvas-soft": "var(--color-canvas-soft)",
        "on-secondary-fixed-variant": "#303f91",
        "on-primary-container": "#fffeff",
        "on-tertiary": "#ffffff",
        "primary-container": "#0075de",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#331100",
        "surface-container": "#ecedf7",
        "surface-dim": "#d8dae3",
        "secondary": "#4958aa",
        "accent-pink": "#ff64c8",
        "primary-fixed": "#d5e3ff",
        "outline": "#717784",
        "on-secondary-container": "#283789",
        "on-primary-fixed": "#001b3c",
        "accent-green": "#1aae39",
        "tertiary": "#9b4300",
        "surface-container-high": "#e6e8f1",
        "canvas": "var(--color-canvas)",
        "inverse-primary": "#a8c8ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "8px",
        "md": "16px",
        "xl": "28px",
        "xxs": "4px",
        "sm": "12px",
        "xs": "8px",
        "lg": "24px",
        "xxl": "32px"
      },
      "fontFamily": {
        "button": "var(--font-primary)",
        "title": "var(--font-primary)",
        "body-md": "var(--font-primary)",
        "heading-2": "var(--font-primary)",
        "body-sm": "var(--font-primary)",
        "caption": "var(--font-primary)",
        "heading-1": "var(--font-primary)",
        "heading-3": "var(--font-primary)"
      },
      "fontSize": {
        "button": ["calc(14px * var(--font-size-scale))", "20px"],
        "title": ["calc(18px * var(--font-size-scale))", "24px"],
        "body-md": ["calc(14px * var(--font-size-scale))", "20px"],
        "heading-2": ["calc(24px * var(--font-size-scale))", "32px"],
        "body-sm": ["calc(12px * var(--font-size-scale))", "16px"],
        "caption": ["calc(10px * var(--font-size-scale))", "16px"],
        "heading-1": ["calc(32px * var(--font-size-scale))", "40px"],
        "heading-3": ["calc(20px * var(--font-size-scale))", "28px"]
      },
      "fontWeight": {
        "button": "500",
        "title": "600",
        "body-md": "400",
        "heading-2": "600",
        "body-sm": "400",
        "caption": "400",
        "heading-1": "700",
        "heading-3": "600"
      },
      "lineHeight": {
        "button": "20px",
        "title": "24px",
        "body-md": "20px",
        "heading-2": "32px",
        "body-sm": "16px",
        "caption": "16px",
        "heading-1": "40px",
        "heading-3": "28px"
      }
    },
  },
  plugins: [],
}
