// Utility for generating and managing a 6-Month Academic Exam Calendar
// based on Vietnamese High School Exam Standards (15min tests, Mid-term, End-of-term exams)

export const EXAM_TYPES = {
  MIN_15: {
    key: '15min',
    name: 'Kiểm tra 15 phút',
    shortName: '15 phút',
    difficulty: 'Dễ',
    duration: '15 phút',
    questionCount: 10,
    color: 'bg-accent-sky/20 text-accent-sky border-accent-sky/30',
    badgeBg: 'bg-accent-sky text-white'
  },
  MIDTERM: {
    key: 'midterm',
    name: 'Kiểm tra Giữa kỳ',
    shortName: 'Giữa kỳ',
    difficulty: 'Trung bình',
    duration: '45 phút',
    questionCount: 40,
    color: 'bg-accent-orange/20 text-accent-orange border-accent-orange/30',
    badgeBg: 'bg-accent-orange text-white'
  },
  FINAL: {
    key: 'final',
    name: 'Kiểm tra Cuối kỳ',
    shortName: 'Cuối kỳ',
    difficulty: 'Khó',
    duration: '60 phút',
    questionCount: 50,
    color: 'bg-accent-pink/20 text-accent-pink border-accent-pink/30',
    badgeBg: 'bg-accent-pink text-white'
  }
};

/**
 * Format a Date object to YYYY-MM-DD string
 */
export function formatDateKey(dateObj) {
  const y = dateObj.getFullYear();
  const m = String(dateObj.getMonth() + 1).padStart(2, '0');
  const d = String(dateObj.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

/**
 * Generate a 6-month academic exam schedule starting from specified startDate
 */
export function createAcademicExamSchedule(startDate = new Date(), selectedTopicIds = ['default']) {
  const start = new Date(startDate);
  start.setHours(0, 0, 0, 0);

  // Offset days over 6 months (~180 days / 2 semesters) matching Thông tư 22/2021/TT-BGDĐT THPT structure
  // Each semester has 4 regular tests (15min) + 1 midterm (45min) + 1 final (60min) = 12 total test milestones
  const milestoneOffsets = [
    // HỌC KỲ I (Semester 1: Months 1-3)
    { days: 12, type: EXAM_TYPES.MIN_15, title: 'Kiểm tra 15 phút (Bài 1 - HK1)' },
    { days: 25, type: EXAM_TYPES.MIN_15, title: 'Kiểm tra 15 phút (Bài 2 - HK1)' },
    { days: 45, type: EXAM_TYPES.MIDTERM, title: 'Kiểm tra Giữa Học kỳ I (45 phút)' },
    { days: 65, type: EXAM_TYPES.MIN_15, title: 'Kiểm tra 15 phút (Bài 3 - HK1)' },
    { days: 80, type: EXAM_TYPES.MIN_15, title: 'Kiểm tra 15 phút (Bài 4 - HK1)' },
    { days: 95, type: EXAM_TYPES.FINAL, title: 'Kiểm tra Cuối Học kỳ I (60 phút)' },
    // HỌC KỲ II (Semester 2: Months 4-6)
    { days: 112, type: EXAM_TYPES.MIN_15, title: 'Kiểm tra 15 phút (Bài 5 - HK2)' },
    { days: 125, type: EXAM_TYPES.MIN_15, title: 'Kiểm tra 15 phút (Bài 6 - HK2)' },
    { days: 142, type: EXAM_TYPES.MIDTERM, title: 'Kiểm tra Giữa Học kỳ II (45 phút)' },
    { days: 155, type: EXAM_TYPES.MIN_15, title: 'Kiểm tra 15 phút (Bài 7 - HK2)' },
    { days: 168, type: EXAM_TYPES.MIN_15, title: 'Kiểm tra 15 phút (Bài 8 - HK2)' },
    { days: 180, type: EXAM_TYPES.FINAL, title: 'Kiểm tra Cuối Học kỳ II (60 phút)' }
  ];

  const milestones = milestoneOffsets.map((ms, index) => {
    const msDate = new Date(start);
    msDate.setDate(msDate.getDate() + ms.days);
    const dateKey = formatDateKey(msDate);

    return {
      id: `ms-${index + 1}-${Date.now()}`,
      date: dateKey,
      title: ms.title,
      typeKey: ms.type.key,
      typeName: ms.type.name,
      shortName: ms.type.shortName,
      difficulty: ms.type.difficulty,
      duration: ms.type.duration,
      questionCount: ms.type.questionCount,
      topicIds: [...selectedTopicIds],
      autoRender: false,
      status: 'pending', // pending | ready | completed
      result: null // stored when completed
    };
  });

  const endDate = new Date(start);
  endDate.setMonth(endDate.getMonth() + 6);

  return {
    id: `academic-calendar-${Date.now()}`,
    createdAt: Date.now(),
    startDate: formatDateKey(start),
    endDate: formatDateKey(endDate),
    topicIds: [...selectedTopicIds],
    milestones
  };
}

/**
 * Calculate dynamic status for a milestone:
 * - 'completed': Exam taken and result saved
 * - 'rendered': Exam generated by Gemini & waiting to be taken
 * - 'ready': Scheduled date reached (date <= today) & ready to render
 * - 'pending': Future date (date > today) & pending
 */
export function getMilestoneStatus(milestone) {
  if (!milestone) return 'pending';
  if (milestone.status === 'completed') return 'completed';
  if (milestone.status === 'rendered') return 'rendered';
  const today = formatDateKey(new Date());
  if (milestone.date <= today) return 'ready';
  return 'pending';
}

/**
 * Helper to check if an exam date has arrived (date <= today)
 */
export function isExamDateReached(examDateKey) {
  const today = formatDateKey(new Date());
  return examDateKey <= today;
}
